create database vehiclerental;
use vehiclerental
create table vehicle (
vid int primary key,
vehicle_name varchar (30),
vehicle_type varchar (15),
brand varchar (10),
model_year int ,
status varchar (20),
fuel_type varchar (10) ,
rent_per_day decimal(10,2) 

);


create table vehicle_customer(
cid int primary key ,
customer_name varchar (10),
phone_number varchar (10) not null,
age int,
licence_number varchar (20),
address varchar (20)
);

create table  booking  (
Bid int primary key ,
cid int  not null ,
vid int not null,
booking_date date  ,
start_date  date ,
end_date  date  ,
payment_status varchar (20),
bill_amount decimal (10,3)


);


INSERT INTO Vehicle VALUES
(1, 'Swift', 'Car', 'Maruti', 2022, 'Available', 'Petrol', 1500),
(2, 'Creta', 'Car', 'Hyundai', 2023, 'Rented', 'Diesel', 2500),
(3, 'Activa 6G', 'Bike', 'Honda', 2022, 'Available', 'Petrol', 700),
(4, 'Royal Enfield', 'Bike', 'Enfield', 2021, 'Maintenance', 'Petrol', 1200),
(5, 'Nexon EV', 'Car', 'Tata', 2024, 'Available', 'Electric', 2200);


INSERT INTO vehicle_customer VALUES
(101, 'Rahul Sharma', '9876543210', 25, 'DL12345', 'Delhi'),
(102, 'Priya Singh', '9876543211', 28, 'DL12346', 'Mumbai'),
(103, 'Aman Kumar', '9876543212', 24, 'DL12347', 'Pune'),
(104, 'Neha Verma', '9876543213', 30, 'DL12348', 'Delhi');

INSERT INTO Booking VALUES
(1001, 101, 1, '2026-09-01', '2026-09-02', '2026-09-04', 'Paid', 4500),
(1002, 102, 2, '2026-09-02', '2026-09-03', '2026-09-05', 'Pending', 7500),
(1003, 101, 3, '2026-09-03', '2026-09-04', '2026-09-06', 'Paid', 2100),
(1004, 103, 2, '2026-09-04', '2026-09-05', '2026-09-07', 'Partial', 5000),
(1005, 104, 1, '2026-09-05', '2026-09-06', '2026-09-08', 'Paid', 4500);

#1Display all vehicles that are currently Available.
select  *  from vehicle
where status = 'Available'

#2Display all Cars with their vehicle name, brand and rent per day
select vehicle_name , brand , rent_per_day from vehicle;

#3Display all Bikes whose rent per day is greater than ₹1,000.
select vehicle_type ,rent_per_day  from vehicle 
where vehicle_type in ('Bike') and  rent_per_day > 1000

#4Display customers whose age is between 25 and 40.
select customer_name ,age from vehicle_customer
where age between 25 and 40

#5Display all bookings where the payment status is Pending.
select  * from booking
where payment_status = 'Pending'

#6Display the customer name, vehicle name, start date and end date for every booking.
select c .customer_name  , v.vehicle_type , b. start_date ,b. end_date from booking b
join  vehicle v
on b.vid = v.vid
join vehicle_customer c
on b.cid = c.cid


#7Display customer name, phone number, vehicle name and bill amount for all bookings
select c. customer_name  , c. phone_number  ,v.vehicle_name ,  b.bill_amount  from vehicle_customer c
join  vehicle v
on c.cid = c.cid
join booking b
on b.vid = v.vid


#8 Display all bookings for Cars along with customer details.
select  * from booking b
left join  vehicle v
on v.vid =b.vid
left join vehicle_customer c
on c.cid = b.cid
where v.vehicle_type = 'Car'

#9 Display all customers who have made at least one booking.
select  distinct c. customer_name  from vehicle_customer c
join booking b
on b.cid=c.cid

#10 Display all vehicles that have been booked at least once
select distinct  v.vehicle_name  from vehicle v
join  booking b
on v.vid =b.vid

#11 Find the total rental revenue generated by the company.
select sum(bill_amount) as total_revenue from booking
#12Find the average booking bill.
 select avg(bill_amount) as avg_booking from booking
 #13Find the highest booking bill.
 select max(bill_amount) as high_booking from booking
 #14Find the total number of bookings.
 select count(bid) as total_booking from booking
 #15Find the total revenue generated from Cars and Bikes separately.
 select sum(rent_per_day) as total_revenue from vehicle
 group by vehicle_type
 
 #16Find the number of bookings made by each customer.
select c.customer_name , count( distinct b.bid) as total_booking from booking b
join vehicle_customer c
on c.cid = b.cid
group by c.cid

#17 Find the total amount spent by each customer.
#Display customers in descending order of total spending.
select  c.  customer_name   , sum( b.bill_amount) as total_amount from  vehicle_customer c
join booking b
on b.cid = c.cid
group by customer_name 
order by total_amount desc

#18Find the number of bookings for each vehicle.
#Display:Vehicle_NameNumber_of_Bookings

select count(distinct b.bid) as number_of_booking ,vehicle_name  from booking b
join vehicle v
on v.vid = b.vid
group by vehicle_name 

#19Find vehicle types having more than 3 bookings.
select v.vehicle_type ,  count(b.bid ) as total_booking from vehicle v
join booking b
on b.vid=v.vid
group by v.vehicle_type
having count( b.bid)>3
#20Find the top 3 customers who have generated the highest rental revenue.
#Display:Customer_Name Number_of_Bookings Total_Spending
select c.customer_name  , count(b.bid)as total_of_booking , sum(b.bill_amount) as total_spending from booking b
join vehicle_customer c
on b.cid =c.cid
group by c.customer_name
order by Total_spending desc
limit 3


select * from vehicle
select * from vehicle_customer
select * from booking